# Generated by Django 5.2.9 on 2025-12-31 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GRADING", "Grading"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("time_taken_minutes", models.PositiveIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="exams.exam"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("answer_text", models.TextField()),
                ("marks_obtained", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("similarity_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("graded_by_service", models.CharField(blank=True, max_length=20)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exams.question")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="submissions.submission"
                    ),
                ),
            ],
            options={
                "db_table": "answers",
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["uuid"], name="submissions_uuid_a046a3_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["student"], name="submissions_student_51a963_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["exam"], name="submissions_exam_id_d9a457_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_dcc854_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["submitted_at"], name="submissions_submitt_9b96b8_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["student", "exam", "status"], name="student_submission_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("student", "exam")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["uuid"], name="answers_uuid_e49672_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["submission"], name="answers_submiss_1e8504_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question"], name="answers_questio_3d2018_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["submission", "question"], name="answer_submission_question_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "question")},
        ),
    ]
