# Generated by Django 5.2.9 on 2025-12-31 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="courses", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("passing_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("start_time", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exams", to="exams.course"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice Question"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("ESSAY", "Essay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.PositiveIntegerField()),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("grading_rubric", models.JSONField(blank=True, null=True)),
                ("case_sensitive", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="exams.exam"
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["uuid"], name="courses_uuid_4d6d0c_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["code"], name="courses_code_fa42f1_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["instructor"], name="courses_instruc_77fba4_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["is_active"], name="courses_is_acti_25e634_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["uuid"], name="exams_uuid_7809c3_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["course"], name="exams_course__86c1c6_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["is_active"], name="exams_is_acti_5cee66_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["start_time"], name="exams_start_t_bab18d_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["is_active", "start_time", "end_time"], name="exam_availability_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["uuid"], name="questions_uuid_8edc8d_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["exam"], name="questions_exam_id_519196_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["exam", "order"], name="question_exam_order_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("exam", "order")},
        ),
    ]
